### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by agil-NUBBA** [inorganik/countUp.js-angular2#1]
Hi, almost sure it's the same issue: https://github.com/inorganik/countUp.js/issues/154

```
WARNING in ./node_modules/countup.js-angular2/dist/countUp.module.js
15:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
    at CommonJsRequireContextDependency.getWarnings (C:\xampp\htdocs\proyectos\my-project\panel\node_modules\webpack\lib\dependencies\CommonJsRequireContextDependency.js:27:4)
    at Compilation.reportDependencyErrorsAndWarnings (C:\xampp\htdocs\proyectos\my-project\panel\node_modules\webpack\lib\Compilation.js:677:24)
    at Compilation.finish (C:\xampp\htdocs\proyectos\my-project\panel\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (C:\xampp\htdocs\proyectos\my-project\panel\node_modules\webpack\lib\Compiler.js:512:17)
    at C:\xampp\htdocs\proyectos\my-project\panel\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\xampp\htdocs\proyectos\my-project\panel\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (C:\xampp\htdocs\proyectos\my-project\panel\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

webpack: Compiled with warnings.
```
![mozilla firefox](https://user-images.githubusercontent.com/27765833/29655666-153da5ac-88b2-11e7-84ce-c9fa15370345.jpg)

I'm currently working under Angular 4.3.6 / TS 2.4.0, haven't tried with previous versions
```
@angular/cli: 1.3.2
node: 6.11.0
os: win32 x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/upgrade: 4.3.6
@angular/cli: 1.3.2
@angular/compiler-cli: 4.3.6
```

thanks in advance.

**Comment by inorganik** [comment]
Can you make a PR to fix? Would an index.js file help? I'm just not knowledgeable enough about Angular2+ to help.

**Comment by inorganik** [comment]
Hi, please try with the latest version (1.1.0). I just released it. Working in Angular 4. 

If it works, please close this issue.

**Comment by agil-NUBBA** [comment]
Doesn't work:

```
WARNING in ./node_modules/countup.js-angular2/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings ([..]\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings ([..]\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish ([..]\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err ([..]\node_modules\webpack\lib\Compiler.js:502:17)
    at [..]\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain ([..]\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err ([..]\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/countup.js-angular2/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/countup.js-angular2/dist/bundles/countup.js-angular2.umd.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

**Comment by inorganik** [comment]
I just tested again installing the npm module with `yarn add countup.js-angular2` and it worked fine. 

Try this:
1. remove the countup.js-angular2 dep from package.json
1. run `git clean -Xfd` to blow away your node_modules folder
1. **carefully** follow the instructions on the README to install it again

**Comment by Jdruwe** [comment]
I am getting the same error as @agil-NUBBA

**Comment by FateTrader** [comment]
I'm getting the same warning errors (attached screenshot below)

1. I've installed it
`npm install countup.js-angular2 --save`
3. Added to app.module.ts
```
import { CountUpModule } from 'countup.js-angular2';
imports: [CountUpModule],
```
2. I'm serving project without the --aot just in case
`ng serve --open`

![capture](https://user-images.githubusercontent.com/30724183/34873427-049ff462-f78d-11e7-9d4f-524ded5a0152.PNG)

**Comment by inorganik** [comment]
Ok, I was able to repro in a brand new angular project. I'll work on it...

**Comment by inorganik** [comment]
Ok, should be working now, worked on my test project. I had to mess with the deps in package.json

Please everyone, change the version in package.json to 1.1.1:
```json
"countup.js-angular2": "^1.1.1",
```
and `yarn install` and try again

**Comment by agil-NUBBA** [comment]
Now it's working, thank you.
